---
# Source: openebs/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lsmoura-openebs
  labels:
    app: openebs
    chart: openebs-2.3.0
    release: lsmoura
    heritage: Helm
