---
# Source: openebs/templates/service-maya-apiserver.yaml
apiVersion: v1
kind: Service
metadata:
  name: lsmoura-openebs-apiservice
  labels:
    app: openebs
    chart: openebs-2.3.0
    release: lsmoura
    heritage: Helm
    openebs.io/component-name: maya-apiserver-svc
spec:
  ports:
  - name: api
    port: 5656
    targetPort: 5656
    protocol: TCP
  selector:
    app: openebs
    release: lsmoura
    component: apiserver
  sessionAffinity: None
